class { 'zabbix::agent':
  pidFile              => '/var/run/zabbix/zabbix_agentd.pid',
  logFile              => '/var/log/zabbix/zabbix_agentd.log',
  logFileSize          => undef,
  debugLevel           => undef,
  sourceIP             => undef,
  enableRemoteCommands => '1',
  logRemoteCommands    => undef,
  server               => 'zabbix.example.com',
  listenPort           => undef,
  listenIP             => undef,
  startAgents          => undef,
  serverActive         => undef,
  hostname             => undef,
  hostnameItem         => undef,
  hostMetadata         => undef,
  hostMetadataItem     => undef,
  refreshActiveChecks  => undef,
  bufferSend           => undef,
  bufferSize           => undef,
  maxLinesPerSecond    => undef,
  allowRoot            => undef,
  zabbix_alias         => undef,
  timeout              => undef,
  include              => undef,
  unsafeUserParameters => undef,
  userParameter        => ['test,hostname', 'test2,echo help'],
}
